Install missing libraries

In [2]:
pip install scikit-learn

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 5.6 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.0 MB 4.5 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.0 MB 4.2 MB/s eta 0:00:03
   ----------- ---------------------------- 3.1/11.0 MB 4.3 MB/s eta 0:00:02
   -------------- ------------------------- 3.9/11.0 MB 4.2 MB/s eta 0:00:02
   ------------------ --------------------- 5.0/11.0 MB 4.1 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.0 MB 4.1 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.0 MB 4.2 MB/s eta 0:00:01
   ---------------------------- ----------- 7.9/11.0 MB 4.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/11.0 MB 4.3 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 4.1 MB/s eta 0:00:01
   --


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## import required libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler,OrdinalEncoder,OneHotEncoder
from sklearn.impute import SimpleImputer

Load dataset

In [51]:
df = pd.read_csv('./Sample_Data.csv')


In [52]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Correlation analysis between the numerical columns      

In [6]:
df.corr(numeric_only=True)


Age    Salary
Age     1.000000  0.982495
Salary  0.982495  1.000000

Check for missing values

In [53]:
df.isnull().sum()


Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

Impute Missing Values with Constant Value. We will impute Missing Values with Constant Value

In [54]:
Imputer = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=0)


Fill missing values in specific columns with the constant value defined above.

In [55]:
df.iloc[:,1:3]=Imputer.fit_transform(df.iloc[:,1:3])


In [56]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Impute Missing Values with Mean

In [11]:
Imputer=SimpleImputer(missing_values=np.nan,strategy='mean')


Apply Mean Imputation

In [57]:
df.iloc[:,1:3]=Imputer.fit_transform(df.iloc[:,1:3])


In [60]:
df


Country   Age    Salary Purchased
0   France  0.88  0.867470        No
1    Spain  0.54  0.578313       Yes
2  Germany  0.60  0.650602        No
3    Spain  0.76  0.734940        No
4  Germany  0.80  0.000000       Yes
5   France  0.70  0.698795       Yes
6    Spain  0.00  0.626506        No
7   France  0.96  0.951807       Yes
8  Germany  1.00  1.000000        No
9   France  0.74  0.807229       Yes

In [58]:
MinMax=MinMaxScaler()
df.iloc[:,1:3]=MinMax.fit_transform(df.iloc[:,1:3])

In [59]:
df

Country   Age    Salary Purchased
0   France  0.88  0.867470        No
1    Spain  0.54  0.578313       Yes
2  Germany  0.60  0.650602        No
3    Spain  0.76  0.734940        No
4  Germany  0.80  0.000000       Yes
5   France  0.70  0.698795       Yes
6    Spain  0.00  0.626506        No
7   France  0.96  0.951807       Yes
8  Germany  1.00  1.000000        No
9   France  0.74  0.807229       Yes

Scales selected columns to a 0-1 range using Min-Max scaling.

In [61]:
St = StandardScaler()
df.iloc[:,1:3]=St.fit_transform(df.iloc[:,1:3])

In [18]:
df

Country       Age    Salary Purchased
0   France  0.673262  0.661970        No
1    Spain -0.584480 -0.426200       Yes
2  Germany -0.362526 -0.154157        No
3    Spain  0.229353  0.163225        No
4  Germany  0.377323 -2.602539       Yes
5   France  0.007398  0.027204       Yes
6    Spain -2.582070 -0.244838        No
7   France  0.969201  0.979353       Yes
8  Germany  1.117171  1.160714        No
9   France  0.155368  0.435268       Yes

Calculates the skewness of numerical columns to check for asymmetry.

In [37]:
df.skew(numeric_only=True)

Age      -1.753019
Salary   -1.760196
dtype: float64

Calculates the kurtosis to measure the tailedness of numerical columns.
Kurtosis is a statistical measure that describes the shape of a data distribution, particularly the extremity of its tails. Unlike skewness, which indicates the symmetry or asymmetry of a distribution, kurtosis focuses on the presence and size of outliers.

In [39]:
df.kurtosis(numeric_only=True)


Age       4.014398
Salary    4.301502
dtype: float64

Encodes categorical values in specific columns with ordinal values. Ordinal Encoding is a technique used to convert categorical (non-numeric) data into numeric values by assigning a unique integer to each category. This encoding is particularly suitable when the categorical data has an inherent order or ranking. For example, categories like “low,” “medium,” and “high” can be represented numerically as 0, 1, and 2, respectively, because there is an order from low to high.

In [62]:
Ordinal = OrdinalEncoder()
df.iloc[:,[0,3]]=Ordinal.fit_transform(df.iloc[:,[0,3]])
df.index

RangeIndex(start=0, stop=10, step=1)

One-Hot Encoding to convert categorical columns into binary columns.

In [63]:
ct = OneHotEncoder(sparse_output=False)
x=pd.DataFrame(ct.fit_transform(df.iloc[:,[0,3]]))
x.index=df.index
x

0    1    2    3    4
0  1.0  0.0  0.0  1.0  0.0
1  0.0  0.0  1.0  0.0  1.0
2  0.0  1.0  0.0  1.0  0.0
3  0.0  0.0  1.0  1.0  0.0
4  0.0  1.0  0.0  0.0  1.0
5  1.0  0.0  0.0  0.0  1.0
6  0.0  0.0  1.0  1.0  0.0
7  1.0  0.0  0.0  0.0  1.0
8  0.0  1.0  0.0  1.0  0.0
9  1.0  0.0  0.0  0.0  1.0

Applies column transformations, using One-Hot Encoding for specific columns and leaving others unchanged.



In [64]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
df = np.array(ct.fit_transform(df))
print(df)

[[1.0 0.0 0.0 0.6732618473780672 0.6619698596295541 0.0]
 [0.0 0.0 1.0 -0.5844800653062344 -0.4261997726382066 1.0]
 [0.0 1.0 0.0 -0.36252561012665196 -0.1541573645712663 0.0]
 [0.0 0.0 1.0 0.22935293701890186 0.16322544484016374 0.0]
 [0.0 1.0 0.0 0.3773225738052904 -2.6025390371737283 1.0]
 [1.0 0.0 0.0 0.0073984818393194275 0.02720424080669361 1.0]
 [0.0 0.0 1.0 -2.5820701619224784 -0.24483816726024626 0.0]
 [1.0 0.0 0.0 0.9692011209508438 0.9793526690409846 1.0]
 [0.0 1.0 0.0 1.1171707577372323 1.160714274418945 0.0]
 [1.0 0.0 0.0 0.15536811862570757 0.435267852907104 1.0]]
